Bug #52043 s4c: fix startup (decoding of objectSid)
Starting S4-Connector only prints "Failed to get SID from S4: 'utf-8' codec can't decode byte 0xed in position 16: invalid continuation byte"
Let it raise the real exception instead, which is:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/main.py", line 301, in <module>
    main()
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/main.py", line 283, in main
    connect()
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/main.py", line 171, in connect
    baseConfig['%s/s4/listener/dir' % CONFIGBASENAME]
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 852, in __init__
    self.s4_search_ext_s(s4_ldap_base, ldap.SCOPE_BASE, 'objectclass=domain', ['objectSid'])[0][1]['objectSid'][0])
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 498, in decode_sid
    sid += "%d" % ord(value[0])
TypeError: ord() expected string of length 1, but int found