Bug #52194: Fix locale.getdefaultlocate() usage
The Python module "locale" contains a hard-coded list `locale_alias` of
aliases, which maps `c.utf8` to `en_US.UTF-8`. (This is wrong for any
application using a language other then English internally!)

It has another bad effects, as `getdefaultlocate()` then returns
`("en_US", "UTF-8")` for the default `C` locale. When passed to
`setlocale()` this will fail when the locale `en_US.UTF-8` is not
available: This happens for example during package build time of USS in
environments, where the Debian package `locale` is not installed and
configured:

> Traceback (most recent call last):
>   File "tests/test_setup_script_profile", line 10, in <module>
>     from univention.management.console.modules.setup.setup_script import Profile  # noqa: E402
>   File "tests/../umc/python/setup/setup_script.py", line 58, in <module>
>     _ = setup_i18n()
>   File "tests/../umc/python/setup/setup_script.py", line 50, in setup_i18n
>     locale.setlocale(locale.LC_ALL, locale.getdefaultlocale())
>   File "/usr/lib/python2.7/locale.py", line 581, in setlocale
>     return _setlocale(category, locale)
> locale.Error: unsupported locale setting

(Another bug here is that code is already executed by merely importing a
module!)

Actually `getdefaultlocale()` tries to implement the same logic in
Python which `setlocale()` already does in C when called with
`locale=""`: It checks the environment variables `LC_ALL`, `LC_CTYPE`,
`LANG` and `LANGUAGE` in that order and selects the first one.

Just use `setlocale(LC_ALL, "")` whenever possible.

Fix the case in UMC where only `LC_ALL` was used and not the other 3.

Note 1: `getlocale()` returns the same information as
`getdefaultlocale()` *after* the locale has been set through
`setlocale()`: Both functions use `normalize()` internally, which does
the `C` to `en_US` translation. As `i18n` uses `getlocal()` internally
by default, just remove the un-needed argument for passing the locale
explicitly.

Note 2: The only change is behavior is for applications, which actually
ship `en_US` translation explicitly: For `LANG=C` they would now get the
requested `C` locale instead of the `en_US` locale they formerly got
wrongly.

QA:
> $ python -c 'import locale as l;print(l.getdefaultlocale());l.setlocale(l.LC_ALL,"");print(l.getlocale())'
> ('de_DE', 'UTF-8')
> ('de_DE', 'UTF-8')
> $ LANG=C.UTF-8 python -c 'import locale as l;print(l.getdefaultlocale());l.setlocale(l.LC_ALL,"");print(l.getlocale())'
> ('en_US', 'UTF-8')
> ('en_US', 'UTF-8')
> $ LANG=en_US.UTF-8 python -c 'import locale as l;print(l.getdefaultlocale());l.setlocale(l.LC_ALL,"");print(l.getlocale())'
> ('en_US', 'UTF-8')
> Traceback (most recent call last):
...
> locale.Error: unsupported locale setting