Bug #52043: fix calling str2dn type
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1051, in resync_rejected_ucs
    if self.__sync_file_from_ucs(filename, append_error=' rejected'):
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 891, in __sync_file_from_ucs
    mapped_object = self._object_mapping(key, object, 'ucs')
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1842, in _object_mapping
    object = function(self, object, dn_mapping_stored, isUCSobject=(object_type == 'ucs'))
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 463, in group_dn_mapping
    return samaccountname_dn_mapping(s4connector, given_object, dn_mapping_stored, isUCSobject, 'group', u'cn', u'posixGroup', 'cn', u'group')
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 337, in samaccountname_dn_mapping
    exploded_dn = str2dn(unicode_to_utf8(dn)) if six.PY2 else str2dn(dn)
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 202, in str2dn
    return ldap.dn.str2dn(fix_dn(dn))
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 195, in fix_dn
    return dn.replace('\\?', '?') if dn is not None else dn
TypeError: a bytes-like object is required, not 'str'