Bug #52043 s4c: fix loading pickle files
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/main.py", line 301, in <module>
    main()
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/main.py", line 283, in main
    connect()
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/main.py", line 214, in connect
    change_counter = s4.poll_ucs()
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1104, in poll_ucs
    (dn, new, old, old_dn) = pickle.load(fob)
TypeError: a bytes-like object is required, not 'str'